// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Shamyr.Expendity.Server.Service.Database;

namespace Shamyr.Expendity.Server.Service.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Shamyr.Expendity.Server.Entities.ExpenseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CreatorUserId")
                        .HasColumnType("integer")
                        .HasColumnName("creator_user_id");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("date_added");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<int?>("LastUpdaterUserId")
                        .HasColumnType("integer")
                        .HasColumnName("last_updater_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<int?>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_expenses");

                    b.HasIndex("CreatorUserId")
                        .HasDatabaseName("ix_expenses_creator_user_id");

                    b.HasIndex("DateAdded")
                        .HasDatabaseName("ix_expenses_date_added");

                    b.HasIndex("LastUpdaterUserId")
                        .HasDatabaseName("ix_expenses_last_updater_user_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_expenses_project_id");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_expenses_type_id");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("Shamyr.Expendity.Server.Entities.ExpenseTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.HasKey("Id")
                        .HasName("pk_expense_types");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_expense_types_project_id");

                    b.ToTable("ExpenseTypes");
                });

            modelBuilder.Entity("Shamyr.Expendity.Server.Entities.ProjectEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CurrencyType")
                        .HasColumnType("integer")
                        .HasColumnName("currency_type");

                    b.Property<bool>("Deleted")
                        .HasColumnType("boolean")
                        .HasColumnName("deleted");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Shamyr.Expendity.Server.Entities.ProjectInviteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("IsMultiUse")
                        .HasColumnType("boolean")
                        .HasColumnName("is_multi_use");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<int>("ProjectPermissionType")
                        .HasColumnType("integer")
                        .HasColumnName("project_permission_type");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("token");

                    b.HasKey("Id")
                        .HasName("pk_project_invites");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_invites_project_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_project_invites_token");

                    b.ToTable("ProjectInvites");
                });

            modelBuilder.Entity("Shamyr.Expendity.Server.Entities.ProjectPermissionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer")
                        .HasColumnName("project_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_project_permissions");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_project_permissions_project_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_project_permissions_user_id");

                    b.HasIndex("UserId", "ProjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_project_permissions_user_id_project_id");

                    b.ToTable("ProjectPermissions");
                });

            modelBuilder.Entity("Shamyr.Expendity.Server.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FamilyName")
                        .HasColumnType("text")
                        .HasColumnName("family_name");

                    b.Property<string>("GivenName")
                        .HasColumnType("text")
                        .HasColumnName("given_name");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_id");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("SubjectId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_subject_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Shamyr.Expendity.Server.Entities.ExpenseEntity", b =>
                {
                    b.HasOne("Shamyr.Expendity.Server.Entities.UserEntity", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .HasConstraintName("fk_expenses_users_creator_user_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shamyr.Expendity.Server.Entities.UserEntity", "LastUpdaterUser")
                        .WithMany()
                        .HasForeignKey("LastUpdaterUserId")
                        .HasConstraintName("fk_expenses_users_last_updater_user_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Shamyr.Expendity.Server.Entities.ProjectEntity", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("fk_expenses_projects_project_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shamyr.Expendity.Server.Entities.ExpenseTypeEntity", "Type")
                        .WithMany("Expenses")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("fk_expenses_expense_types_type_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatorUser");

                    b.Navigation("LastUpdaterUser");

                    b.Navigation("Project");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Shamyr.Expendity.Server.Entities.ExpenseTypeEntity", b =>
                {
                    b.HasOne("Shamyr.Expendity.Server.Entities.ProjectEntity", "Project")
                        .WithMany("ExpenseTypes")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("fk_expense_types_projects_project_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Shamyr.Expendity.Server.Entities.ProjectInviteEntity", b =>
                {
                    b.HasOne("Shamyr.Expendity.Server.Entities.ProjectEntity", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("fk_project_invites_projects_project_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Shamyr.Expendity.Server.Entities.ProjectPermissionEntity", b =>
                {
                    b.HasOne("Shamyr.Expendity.Server.Entities.ProjectEntity", "Project")
                        .WithMany("Permissions")
                        .HasForeignKey("ProjectId")
                        .HasConstraintName("fk_project_permissions_projects_project_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shamyr.Expendity.Server.Entities.UserEntity", "User")
                        .WithMany("ProjectPermissions")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_project_permissions_users_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Shamyr.Expendity.Server.Entities.ExpenseTypeEntity", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("Shamyr.Expendity.Server.Entities.ProjectEntity", b =>
                {
                    b.Navigation("ExpenseTypes");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Shamyr.Expendity.Server.Entities.UserEntity", b =>
                {
                    b.Navigation("ProjectPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
